### ISSUE TITLE
Define a model as ODEs

### ISSUE THREAD

**Issue by amitvtaneja** [andrewhooker/PopED#16]
Hi Andy

Can a model be defined as a system of ODEs, since the example mentioned is for a one compartment model, analytical solution?
If so, could you please provide an example for a 2 cmgt model, oral absorption.

Thanks in advance

Amit Taneja

**Comment by andrewhooker** [comment]
Hi Amit,

Yes.  Please see examples 1.c, 2.c, 8, 9 and 10 at https://github.com/andrewhooker/PopED/tree/master/inst/examples 

Example 9 has what you are looking for.

Best regards,
Andy

**Comment by amitvtaneja** [comment]
Many Thanks Andy

Best regards

Amit

**Comment by liangqiongyue** [comment]
Hi andrewhooker
    When I run the Example 9 (2 cmgt model, oral absorption) I run into some problems. The following error message appears when I run two lines of code:
###########
**> system("R CMD SHLIB two_comp_oral_CL.c")**
C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:275: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:268: warning: ignoring old commands for target `.m.o'
make: *** No rule to make target `two_comp_oral_CL.o', needed by `two_comp_oral_CL.dll'.  Stop.
[1] 1
**> dyn.load(paste("two_comp_oral_CL", .Platform$dynlib.ext, sep = ""))**
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/liangq3/AppData/Local/R/win-library/4.2/PopED/two_comp_oral_CL.dll':
  LoadLibrary failure:  The specified module could not be found.
###########
May I ask how to solve this problem? Thank you very much for your help!

**Comment by liangqiongyue** [comment]
_> Hi andrewhooker When I run the Example 9 (2 cmgt model, oral absorption) I run into some problems. The following error message appears when I run two lines of code: ########### **> system("R CMD SHLIB two_comp_oral_CL.c")** C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:275: warning: overriding commands for target `.m.o' C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:268: warning: ignoring old commands for target `.m.o' make: *** No rule to make target `two_comp_oral_CL.o', needed by `two_comp_oral_CL.dll'. Stop. [1] 1 **> dyn.load(paste("two_comp_oral_CL", .Platform$dynlib.ext, sep = ""))** Error in inDL(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'C:/Users/liangq3/AppData/Local/R/win-library/4.2/PopED/two_comp_oral_CL.dll': LoadLibrary failure: The specified module could not be found. ########### May I ask how to solve this problem? Thank you very much for your help!_

--------------------------------------------------------------------------------------
I found a solution to this problem, Just first installing Rtools42 first can be solved. 
(https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html)
