### ISSUE TITLE
Idential sampling points result in different RSE. Is this a bug or normal?

### ISSUE THREAD

**Issue by Mike-Hood** [andrewhooker/PopED#17]
Hi Andrewhooker ,

I am new to this tool.  I found: 

**Only one time point at the time 1 hour:**
![image](https://user-images.githubusercontent.com/33563378/32685977-5b40368c-c66a-11e7-9441-75db068c28be.png)

**Two time points at the time 1 hour:**
![image](https://user-images.githubusercontent.com/33563378/32685971-4bf3a5a6-c66a-11e7-8272-352252310462.png)

The bpop[2] is quite different.  I am wondering how this happens.

Thank you,

Mike

**Comment by andrewhooker** [comment]
Hi

If you take two samples at the same time point then (assuming that there is no correlation between samples ... as is common in PKPD models) taking 2 samples will give twice as much information as 1 sample.  See for example Nyberg, J., Hoglund, R., Bergstrand, M., Karlsson, M. O. and Hooker, A. C. (2012) ‘Serial correlation in optimal design for nonlinear mixed effects models’, J Pharmacokinet Pharmacodyn, 39(3), pp. 239–249. doi: 10.1007/s10928-012-9245-5.

Best regards,
Andrew
