### ISSUE TITLE
Manually updating the number of samples as an alternative to opt_samps in R?

### ISSUE THREAD

**Issue by michielve** [andrewhooker/PopED#42]
Hello,

Thank you for your work on PopED.
As with issue #40, I am trying to optimize the number of samples using a function that is not yet available in the R version of PopED.

Before this function gets implemented, I am wondering whether it would be a correct approach to run multiple optimization procedures while testing different designs (e.g. with 4 to 20 samples per subject) and judging the output?

If this is possible, what is the best approach to compare the different designs since more samples will always provide more information? Can this comparison be done by comparing the OFV? Plotting the mean RSE of the parameters over the number of samples? Determining a 'significant' change in the efficiency? 

Thank you for your suggestions,

Michiel van Esdonk

**Comment by andrewhooker** [comment]
Hi Michiel,

I think your strategy makes sense.  Adding samples will always give more information and you will then need to determine when you are satisfied with the amount of information.  As you suggest, using a cutoff level for OFV, efficiency or RSE of certain parameters may be appropriate, and will be case specific I believe.

Andrew
