### ISSUE TITLE
parallel computation for plot_efficiency_of_windows()

### ISSUE THREAD

**Issue by timwaterhouse** [andrewhooker/PopED#50]
Hi Andy,

Would it be possible to implement parallel computation in `plot_efficiency_of_windows()`?  I see some commented out references to something called `bParallel` in the code, so I wonder if this is something you've already considered.

Thanks,
Tim

**Comment by andrewhooker** [comment]
Hi

Yes, certainly possible. Do you have a slow calculation you need to speed up?

Andy

Andrew Hooker, Ph.D.
Professor of Pharmacometrics
Dept. of Pharmaceutical Biosciences
Uppsala University
Box 591, 751 24, Uppsala, Sweden
Phone: +46 18 471 4355
Mobile: +46 768 000 725
www.farmbio.uu.se/research/researchgroups/pharmacometrics/

**Comment by timwaterhouse** [comment]
I'm using an ODE model (with mrgsolve), and it was taking 15-20 minutes to run 100 simulations. Would be nice to speed that up if possible.

Tim

**Comment by andrewhooker** [comment]
Now included!

**Comment by timwaterhouse** [comment]
Very nice, thanks Andy!
