### ISSUE TITLE
problem with tests run by AppVeyor

### ISSUE THREAD

**Issue by Vincent-AC** [andrewhooker/PopED#51]
Hello,

I recently issued a pull request with minor updates to the code written to enable parallelisation of poped_optim with mrgsolve models, and the automatic tests ran by appveyor failed. 
After a bit of investigation it is due to the test called "ed_laplace_ofv works", where the following command fails when ran by AppVeyor :
`  expect_warning(expect_error(poped_optim(poped_db,opt_xt=T,parallel = T, d_switch=0,use_laplace=T)))`

However when I download the archive with the tests and ran them locally, the code runs correctly (meaning that I get an error and a warning by the poped_optim function).

I do not know enough about these automated tests to propose a fix, but thought I would let you know anyways !

**Comment by andrewhooker** [comment]
Hi Vincent,

I appreciate you sending the pull request! I will take a look at the request in the next day or two, I'm sure the appveyor thing is fixable without too much effort.

**Comment by andrewhooker** [comment]
Fixed now.
