### ISSUE TITLE
Different results when running the optimization R-script in popED in Windows and Mac

### ISSUE THREAD

**Issue by Anks2030** [andrewhooker/PopED#55]
I tried running the sample optimization R-script on Windows and took around 3.5 h, so decided to check what happens if I run the  same script on Mac. 
1. It ran within 1h on Mac
2. Surprising the %RSE on the optimization results were lower as compared to results from windows. Mac showed better precision on fixed effects and BSV parameters.

Does anyone have any experience with that?
@andrewhooker: Will it be possible for you too share your thoughts and how I can avoid such discrepancy? Thanks in advance

Ankur Sharma

**Comment by andrewhooker** [comment]
Hi Ankur,

I don't think you give enough information for me to give an explanation of what you report.  A few thoughts:

1.  The speed on windows and Mac depend on the software but also the hardware.  What sort of windows machine (type, number and speed of the cpu, amount of RAM) are you using?  What about for your Mac?  If the hardware is not comparable then comparing the speed between the two operating systems does not make sense.
2. What optimization options were you using and on which problem.  If you are using `poped_optim` then there are a series of optimization algorithms that are used.  Some of those algorithms have random components, so unless you set the seed number before running the optimization you may get different results.  The default options in `poped_optim` are set to get approximately the same answers when running the function with different seed numbers but for complicated design problems these default values may need to be changed.

Best regards, 
Andy

**Comment by Anks2030** [comment]
Thanks for your suggestions. I used the seed number and it provides similar results across different machines.
