### ISSUE TITLE
poped_optim vs. poped_optimize

### ISSUE THREAD

**Issue by sibojan** [andrewhooker/PopED#7]
In the function reference, those two functions both serve for "Optimization main module for PopED". Is there any distinction between them?  Which one is typically used for the purpose of optimization?
Thanks.

**Comment by andrewhooker** [comment]
Hi

poped_optim is the newer version of our optimization module, and should, in general, perform better.  poped_optimize is there mostly for back compatibility.

Best regards,
Andrew

**Comment by sibojan** [comment]
Thank you for the clarification. 
Sibo
