### ISSUE TITLE
Errors in runing example "ex.8.tmdd_qss_one_target_compiled.R"

### ISSUE THREAD

**Issue by sibojan** [andrewhooker/PopED#8]
I have ran the entire file with complied model. The script complain until I reached the optimization step:
`output  <- poped_optim(poped.db.2,opt_xt = F, opt_a = T, parallel=T, method = c("LS"))`

The error message is:
![snap37](https://user-images.githubusercontent.com/11802171/27563654-d33a4154-5a87-11e7-83c4-237845f69189.jpg)

Thank you,

**Comment by andrewhooker** [comment]
Hi.

Looks like you are running on windows.  In that case, when running compiled code in parallel, you need to specify the names of the DLLs to pass to the different nodes (computer processors) where the process is running.  After compilation of the you should see the names of the DLLs that are produced in your working directory ... just use the command (replace with real DLL file names):

```R
output <- poped_optim(poped.db.2,opt_xt = F, opt_a = T, parallel=T, method = c("LS"), 
                                         dlls = c("this_file","that_file")) 
```

For more information you can look at ```?start_parallel```

Best regards,
Andrew

**Comment by sibojan** [comment]
There is only one DLL file under my working directory:  tmdd_qss_one_target.dll.

So I change the script to:
`output <- poped_optim(poped.db.2,opt_xt = F, 
                      opt_a = T, parallel=T, method = c("LS"),
                      dlls = c('tmdd_qss_one_target'))  `

It works very well.

Thank you,
