### ISSUE TITLE
The purpose of "model_switch"

### ISSUE THREAD

**Issue by sibojan** [andrewhooker/PopED#9]
The term "model _switch"  is included in a couple of example files.

In ex1,  the "model _switch"  is not defined.
In ex3b, it is defined as model_switch=c(1,1,1,1,1,2,2,2,2,2).

Is there any special purpose for this term?

Thanks.

**Comment by andrewhooker** [comment]
If you define a PK and a PD model then you need a way to define where a measurement will be made.  Model_switch accomplishes this.

Best regards,
Andrew

**Comment by sibojan** [comment]
Hi Andrew,
Thank you for the reply. It seems that  "model _switch" is required as a place holder for the function even you have PK models alone.  It that correct?

**Comment by andrewhooker** [comment]
You never have to define model_switch if you only have one model (one response).  However, the functions ff_fun and ferror_fun should have model_switch as their first argument as you see in the first example.

**Comment by sibojan** [comment]
Thanks for the clarification.
